CREATE TABLE IF NOT EXISTS tax_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_email TEXT NOT NULL,
  w2_income REAL DEFAULT 0,
  net_1099_income REAL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
